// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecordingOfViolations.Models;

#nullable disable

namespace RecordingOfViolations.Migrations
{
    [DbContext(typeof(ViolationContext))]
    [Migration("20221018070129_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RecordingOfViolations.Models.PaymentСheck", b =>
                {
                    b.Property<int>("PaymentСheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentСheckId"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Payer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViolationId")
                        .HasColumnType("int");

                    b.HasKey("PaymentСheckId");

                    b.HasIndex("ViolationId");

                    b.ToTable("PaymentСhecks");
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Reason", b =>
                {
                    b.Property<int>("ReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReasonId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReasonId");

                    b.ToTable("Reasons");

                    b.HasData(
                        new
                        {
                            ReasonId = 1,
                            Name = "Порушення правил користування ременями безпеки або мотошоломами"
                        },
                        new
                        {
                            ReasonId = 2,
                            Name = "Нетверезий стан"
                        },
                        new
                        {
                            ReasonId = 3,
                            Name = "Порушення правил перевезення дітей"
                        },
                        new
                        {
                            ReasonId = 4,
                            Name = "Порушення правил зупинки маршрутних таксі"
                        });
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Offender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Policeman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("ReasonId")
                        .HasColumnType("int");

                    b.HasKey("ViolationId");

                    b.HasIndex("ReasonId");

                    b.ToTable("Violations");

                    b.HasData(
                        new
                        {
                            ViolationId = 1,
                            Address = "вулиця Інститутська, 22",
                            Date = new DateTime(2022, 10, 10, 10, 1, 29, 653, DateTimeKind.Local).AddTicks(607),
                            Offender = "Cпівак Олег",
                            Policeman = "Кукурудза Валерій",
                            Price = 1750m,
                            ReasonId = 3
                        },
                        new
                        {
                            ViolationId = 2,
                            Address = "Львівське шосе, 38/1",
                            Date = new DateTime(2022, 9, 25, 10, 1, 29, 653, DateTimeKind.Local).AddTicks(612),
                            Offender = "Ткачук Петро",
                            Policeman = "Щур Сергій",
                            Price = 510m,
                            ReasonId = 1
                        },
                        new
                        {
                            ViolationId = 3,
                            Address = "вулиця Соборна, 11",
                            Date = new DateTime(2022, 10, 16, 10, 1, 29, 653, DateTimeKind.Local).AddTicks(618),
                            Offender = "Олійник Яна",
                            Policeman = "Щур Сергій",
                            Price = 750m,
                            ReasonId = 4
                        },
                        new
                        {
                            ViolationId = 4,
                            Address = "вулиця Трудова, 6А",
                            Date = new DateTime(2022, 10, 4, 10, 1, 29, 653, DateTimeKind.Local).AddTicks(623),
                            Offender = "Пристувчук Олександр",
                            Policeman = "Кукурудза Валерій",
                            Price = 15000m,
                            ReasonId = 2
                        });
                });

            modelBuilder.Entity("RecordingOfViolations.Models.PaymentСheck", b =>
                {
                    b.HasOne("RecordingOfViolations.Models.Violation", "Violation")
                        .WithMany("PaymentСhecks")
                        .HasForeignKey("ViolationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Violation", b =>
                {
                    b.HasOne("RecordingOfViolations.Models.Reason", "Reason")
                        .WithMany("Violations")
                        .HasForeignKey("ReasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reason");
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Reason", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("RecordingOfViolations.Models.Violation", b =>
                {
                    b.Navigation("PaymentСhecks");
                });
#pragma warning restore 612, 618
        }
    }
}
